// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtlOGU5osL_slerInnhK8KWxIm7NpjSLo',
    appId: '1:1039733825242:web:9a0286683b83475fabcfe3',
    messagingSenderId: '1039733825242',
    projectId: 'instagram-mock-up-6ddde',
    authDomain: 'instagram-mock-up-6ddde.firebaseapp.com',
    storageBucket: 'instagram-mock-up-6ddde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2e5aVTzzf8XYdRtvMV0dv-1dn2QXn1k',
    appId: '1:1039733825242:android:cdeaf2eaffffd587abcfe3',
    messagingSenderId: '1039733825242',
    projectId: 'instagram-mock-up-6ddde',
    storageBucket: 'instagram-mock-up-6ddde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9bG2B81xVxQicxDRE8rDa1Mrrwvml5w',
    appId: '1:1039733825242:ios:5b9f79cc2b78657babcfe3',
    messagingSenderId: '1039733825242',
    projectId: 'instagram-mock-up-6ddde',
    storageBucket: 'instagram-mock-up-6ddde.appspot.com',
    iosClientId:
        '1039733825242-a975v9704of5amcfqssrsvd582jfqabh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI9bG2B81xVxQicxDRE8rDa1Mrrwvml5w',
    appId: '1:1039733825242:ios:5b9f79cc2b78657babcfe3',
    messagingSenderId: '1039733825242',
    projectId: 'instagram-mock-up-6ddde',
    storageBucket: 'instagram-mock-up-6ddde.appspot.com',
    iosClientId:
        '1039733825242-a975v9704of5amcfqssrsvd582jfqabh.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
